version: '2'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.dev
    links:
        - app:app
    ports:
        - "80:80"
        - "443:443"
    restart: on-failure
  app:
    build: ./
    ports:
        - "127.0.0.1:5858:5858"
    restart: on-failure